spring.application.name=merp
server.servlet.context-path=/api

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

# CONFIGURE DATABASE
# BLOCK INCOMING CONNECTIONS TO THE PORT 5432 EXCEPT LOCALHOST
spring.datasource.url=jdbc:postgresql://localhost:5432/merp_db

# ! CHANGE BEFORE DEPLOYMENT
spring.datasource.username=postgres
# ! CHANGE BEFORE DEPLOYMENT
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
# ! CHANGE BEFORE DEPLOYMENT
spring.jpa.show-sql=true

# ! CHANGE BEFORE DEPLOYMENT
jwt.secret=secret
jwt.expiration=86400000

# ! CHANGE BEFORE DEPLOYMENT
cors.allowed-origin=http://localhost:3000

# BLOCK INCOMING CONNECTIONS TO THE PORT 8080 EXCEPT LOCAL NETWORK
server.port=8080

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
