export const TASKS = {
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_USERS: "VIEW_USERS",

  MANAGE_PROFILES: "MANAGE_PROFILES",
  VIEW_PROFILES: "VIEW_PROFILES",

  VIEW_TASKS: "VIEW_TASKS",

  MANAGE_ACCOUNTS: "MANAGE_ACCOUNTS",
  VIEW_ACCOUNTS: "VIEW_ACCOUNTS",

  MANAGE_JOURNAL_ENTRIES: "MANAGE_JOURNAL_ENTRIES",
  VIEW_JOURNAL_ENTRIES: "VIEW_JOURNAL_ENTRIES",

  VIEW_REPORTS: "VIEW_REPORTS",

  MANAGE_ITEMS: "MANAGE_ITEMS",
  VIEW_ITEMS: "VIEW_ITEMS",

  MANAGE_CUSTOMERS: "MANAGE_CUSTOMERS",
  VIEW_CUSTOMERS: "VIEW_CUSTOMERS",

  MANAGE_FISCAL_CONFIGURATION: "MANAGE_FISCAL_CONFIGURATION",
  VIEW_FISCAL_CONFIGURATION: "VIEW_FISCAL_CONFIGURATION",

  MANAGE_PAYMENT_METHODS: "MANAGE_PAYMENT_METHODS",
  VIEW_PAYMENT_METHODS: "VIEW_PAYMENT_METHODS",

  MANAGE_TRANSACTIONS: "MANAGE_TRANSACTIONS",
  VIEW_TRANSACTIONS: "VIEW_TRANSACTIONS",

  MANAGE_INVOICES: "MANAGE_INVOICES",
  VIEW_INVOICES: "VIEW_INVOICES",

  MANAGE_DELIVERY_NOTES: "MANAGE_DELIVERY_NOTES",
  VIEW_DELIVERY_NOTES: "VIEW_DELIVERY_NOTES",

  MANAGE_NOTES: "MANAGE_NOTES",
  VIEW_NOTES: "VIEW_NOTES",
} as const;
