export const TASKS = {
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_USERS: "VIEW_USERS",

  MANAGE_PROFILES: "MANAGE_PROFILES",
  VIEW_PROFILES: "VIEW_PROFILES",

  VIEW_TASKS: "VIEW_TASKS",

  MANAGE_ACCOUNTS: "MANAGE_ACCOUNTS",
  VIEW_ACCOUNTS: "VIEW_ACCOUNTS",

  MANAGE_JOURNAL_ENTRIES: "MANAGE_JOURNAL_ENTRIES",
  VIEW_JOURNAL_ENTRIES: "VIEW_JOURNAL_ENTRIES",

  VIEW_REPORTS: "VIEW_REPORTS",
} as const;
